import type { CollectionConfig } from 'payload'
import { adminOnly } from '@/access/roles'

export const VisitSessions: CollectionConfig = {
  slug: 'visit-sessions',
  labels: {
    singular: 'Sesión de visita',
    plural: 'Sesiones de visita',
  },
  admin: {
    useAsTitle: 'landingPath',
    group: 'Analítica',
    defaultColumns: ['startedAt', 'landingPath', 'country', 'city', 'device', 'isBot', 'pageCount'],
    description:
      'Cada fila es una visita (sesión). El resumen está en Analítica. No se guarda la IP, solo un hash anónimo.',
  },
  defaultSort: '-startedAt',
  access: {
    create: () => false,
    read: adminOnly,
    update: () => false,
    delete: adminOnly,
  },
  fields: [
    { name: 'sessionId', type: 'text', required: true, unique: true, index: true, label: 'ID de sesión' },
    { name: 'visitorId', type: 'text', required: true, index: true, label: 'Visitante anónimo' },
    { name: 'startedAt', type: 'date', required: true, index: true, label: 'Inicio' },
    { name: 'lastSeenAt', type: 'date', required: true, index: true, label: 'Última actividad' },
    { name: 'landingPath', type: 'text', label: 'Página de entrada' },
    { name: 'exitPath', type: 'text', label: 'Página de salida' },
    { name: 'pageCount', type: 'number', defaultValue: 1, label: 'Páginas vistas' },
    {
      name: 'pathLog',
      type: 'json',
      label: 'Recorrido',
      admin: { description: 'Últimas rutas de la sesión (máx. 40).' },
    },
    { name: 'referrer', type: 'text', label: 'Referencia completa' },
    { name: 'referrerHost', type: 'text', index: true, label: 'Sitio de origen' },
    { name: 'utmSource', type: 'text', index: true, label: 'UTM source' },
    { name: 'utmMedium', type: 'text', label: 'UTM medium' },
    { name: 'utmCampaign', type: 'text', index: true, label: 'UTM campaign' },
    { name: 'utmContent', type: 'text', label: 'UTM content' },
    { name: 'utmTerm', type: 'text', label: 'UTM term' },
    {
      name: 'channel',
      type: 'select',
      index: true,
      label: 'Canal',
      options: [
        { label: 'Directo', value: 'direct' },
        { label: 'Orgánico / buscador', value: 'organic' },
        { label: 'Redes', value: 'social' },
        { label: 'Pago / ads', value: 'paid' },
        { label: 'Referido', value: 'referral' },
        { label: 'Bot / indexador', value: 'bot' },
      ],
    },
    { name: 'country', type: 'text', index: true, label: 'País' },
    { name: 'countryCode', type: 'text', label: 'Código de país' },
    { name: 'region', type: 'text', index: true, label: 'Provincia / región' },
    { name: 'city', type: 'text', label: 'Ciudad' },
    {
      name: 'device',
      type: 'select',
      index: true,
      label: 'Dispositivo',
      options: [
        { label: 'Escritorio', value: 'desktop' },
        { label: 'Móvil', value: 'mobile' },
        { label: 'Tablet', value: 'tablet' },
        { label: 'Bot', value: 'bot' },
      ],
    },
    { name: 'browser', type: 'text', label: 'Navegador' },
    { name: 'os', type: 'text', label: 'Sistema' },
    { name: 'isBot', type: 'checkbox', defaultValue: false, index: true, label: 'Es bot o araña' },
    { name: 'botName', type: 'text', label: 'Indexador / bot' },
    { name: 'isBounce', type: 'checkbox', defaultValue: true, label: 'Rebote' },
    { name: 'durationMs', type: 'number', defaultValue: 0, label: 'Duración (ms)' },
    { name: 'reachedCart', type: 'checkbox', defaultValue: false, label: 'Llegó al carrito' },
    { name: 'reachedCheckout', type: 'checkbox', defaultValue: false, label: 'Inició checkout' },
    { name: 'purchased', type: 'checkbox', defaultValue: false, label: 'Compró' },
    { name: 'newsletter', type: 'checkbox', defaultValue: false, label: 'Suscribió newsletter' },
    { name: 'conversionValue', type: 'number', defaultValue: 0, label: 'Valor de conversión (ARS)' },
    {
      name: 'ipHash',
      type: 'text',
      label: 'Huella de IP',
      admin: { description: 'Hash irreversible. No es la IP real.', position: 'sidebar' },
    },
  ],
}
