/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    orders: Order;
    coupons: Coupon;
    customers: Customer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'store-settings': StoreSetting;
    'home-hero': HomeHero;
  };
  globalsSelect: {
    'store-settings': StoreSettingsSelect<false> | StoreSettingsSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cuentas con acceso al panel de control. No son clientes de la tienda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Imágenes y archivos. Se guardan en Cloudinary, no en Vercel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Opcional. Si lo dejás vacío, no pasa nada.
   */
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Categorías (Mujer, Hombre…) y subcategorías (Pantalones, Remeras…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  /**
   * Vacío = categoría principal (Mujer, Hombre, Ofertas…). Si es subcategoría, elegí el padre.
   */
  parent?: (number | null) | Category;
  imageUrl?: string | null;
  description?: string | null;
  menuGroup?: ('destacados' | 'remeras' | 'abrigo' | 'total') | null;
  sort?: number | null;
  /**
   * Solo tiene sentido en categorías principales.
   */
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catálogo de indumentaria con variantes de talle y color.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Se genera solo a partir del nombre al guardar.
   */
  slug?: string | null;
  /**
   * Si lo dejás vacío, se genera a partir del nombre al guardar.
   */
  sku?: string | null;
  description?: string | null;
  price: number;
  /**
   * Mujer, Hombre, Niños, etc. Al elegirla aparecen las subcategorías.
   */
  mainCategory?: (number | null) | Category;
  /**
   * Se listan solo las de la categoría elegida arriba.
   */
  category?: (number | null) | Category;
  image?: (number | null) | Media;
  /**
   * Fotos extra. La tienda muestra la principal y estas como miniaturas.
   */
  images?: (number | Media)[] | null;
  isNew?: boolean | null;
  onSale?: boolean | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  weight: number;
  variants?:
    | {
        /**
         * Se completa solo al guardar: SKU del producto + 1, 2, 3…
         */
        sku?: string | null;
        size: string;
        /**
         * Ej: Negro, Rojo, Crudo
         */
        color: string;
        /**
         * Tocá el cuadro grande para abrir todos los colores, o un circulito rápido. Ese color se ve en la tienda.
         */
        colorHex?: string | null;
        stock: number;
        id?: string | null;
      }[]
    | null;
  stock?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pedidos de la tienda y estado de pago.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  paymentStatus: 'pending' | 'approved' | 'rejected';
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  shippingAddress: {
    street: string;
    floorAppart?: string | null;
    city: string;
    province: string;
    zipCode: string;
  };
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        priceAtPurchase: number;
        variantSku?: string | null;
        size?: string | null;
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  shippingCost: number;
  discount?: number | null;
  couponCode?: string | null;
  loyaltyPointsUsed?: number | null;
  total: number;
  mpPreferenceId?: string | null;
  mpPaymentId?: string | null;
  trackingNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Códigos de descuento y envío gratis.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  type: 'percent' | 'shipping';
  value: number;
  active?: boolean | null;
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cuentas de clientes de la tienda (registro, inicio de sesión y puntos). No acceden al panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  phone?: string | null;
  loyaltyPoints?: number | null;
  birthday?: string | null;
  newsletter?: boolean | null;
  emailVerified?: boolean | null;
  verifyToken?: string | null;
  verifyTokenExpires?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  imageUrl?: T;
  description?: T;
  menuGroup?: T;
  sort?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sku?: T;
  description?: T;
  price?: T;
  mainCategory?: T;
  category?: T;
  image?: T;
  images?: T;
  isNew?: T;
  onSale?: T;
  featured?: T;
  status?: T;
  weight?: T;
  variants?:
    | T
    | {
        sku?: T;
        size?: T;
        color?: T;
        colorHex?: T;
        stock?: T;
        id?: T;
      };
  stock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  paymentStatus?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  shippingAddress?:
    | T
    | {
        street?: T;
        floorAppart?: T;
        city?: T;
        province?: T;
        zipCode?: T;
      };
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        priceAtPurchase?: T;
        variantSku?: T;
        size?: T;
        color?: T;
        id?: T;
      };
  shippingCost?: T;
  discount?: T;
  couponCode?: T;
  loyaltyPointsUsed?: T;
  total?: T;
  mpPreferenceId?: T;
  mpPaymentId?: T;
  trackingNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  active?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  loyaltyPoints?: T;
  birthday?: T;
  newsletter?: T;
  emailVerified?: T;
  verifyToken?: T;
  verifyTokenExpires?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Cuentas, avisos al administrador, captcha y correo SMTP.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings".
 */
export interface StoreSetting {
  id: number;
  loginEnabled?: boolean | null;
  registrationEnabled?: boolean | null;
  /**
   * Requiere SMTP o el enlace se imprime en la consola del servidor. Los clientes existentes pueden seguir entrando.
   */
  requireEmailVerification?: boolean | null;
  minPasswordLength?: number | null;
  sessionDays?: number | null;
  captchaEnabled?: boolean | null;
  captchaProvider?: ('turnstile' | 'recaptcha') | null;
  /**
   * Visible en el sitio. También se puede usar NEXT_PUBLIC_TURNSTILE_SITE_KEY o NEXT_PUBLIC_RECAPTCHA_SITE_KEY.
   */
  captchaSiteKey?: string | null;
  /**
   * Nunca se envía al navegador. También se puede usar TURNSTILE_SECRET_KEY o RECAPTCHA_SECRET_KEY.
   */
  captchaSecretKey?: string | null;
  /**
   * Ahí llegan ventas, registros, mensajes de contacto y alertas de stock bajo.
   */
  adminEmail?: string | null;
  notifySales?: boolean | null;
  notifyRegistrations?: boolean | null;
  notifyContact?: boolean | null;
  lowStockEnabled?: boolean | null;
  /**
   * Si el stock total del producto (suma de variantes) pasa de estar por encima de este número a igual o menor, se envía el email.
   */
  lowStockThreshold?: number | null;
  fromName?: string | null;
  /**
   * Ej: noreply@kaprichos.com.ar
   */
  fromAddress?: string | null;
  smtpHost?: string | null;
  smtpPort?: number | null;
  smtpUser?: string | null;
  smtpPassword?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Carrusel de la portada: imágenes, textos, botones y transiciones.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  /**
   * El orden de esta lista es el orden en la portada. Arrastrá para reordenar.
   */
  slides?:
    | {
        active?: boolean | null;
        /**
         * Subí un archivo (Cloudinary). Si no, usá la URL de abajo.
         */
        image?: (number | null) | Media;
        /**
         * Ej: /catalog/hero-temporada.jpg
         */
        imageUrl?: string | null;
        alt?: string | null;
        objectPosition?: ('center_top' | 'center' | 'center_bottom' | 'left' | 'right') | null;
        /**
         * Ej: Nueva
         */
        eyebrow?: string | null;
        /**
         * Ej: Temporada
         */
        title?: string | null;
        badges?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        /**
         * Ej: /productos
         */
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  autoplay?: boolean | null;
  intervalSeconds?: number | null;
  transition?: ('fade' | 'slide' | 'zoom') | null;
  durationMs?: number | null;
  showArrows?: boolean | null;
  showDots?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings_select".
 */
export interface StoreSettingsSelect<T extends boolean = true> {
  loginEnabled?: T;
  registrationEnabled?: T;
  requireEmailVerification?: T;
  minPasswordLength?: T;
  sessionDays?: T;
  captchaEnabled?: T;
  captchaProvider?: T;
  captchaSiteKey?: T;
  captchaSecretKey?: T;
  adminEmail?: T;
  notifySales?: T;
  notifyRegistrations?: T;
  notifyContact?: T;
  lowStockEnabled?: T;
  lowStockThreshold?: T;
  fromName?: T;
  fromAddress?: T;
  smtpHost?: T;
  smtpPort?: T;
  smtpUser?: T;
  smtpPassword?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        active?: T;
        image?: T;
        imageUrl?: T;
        alt?: T;
        objectPosition?: T;
        eyebrow?: T;
        title?: T;
        badges?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  autoplay?: T;
  intervalSeconds?: T;
  transition?: T;
  durationMs?: T;
  showArrows?: T;
  showDots?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}